### ISSUE TITLE
metacat get_file needs  scope+name

### ISSUE THREAD

**Issue by dougbenjamin** [jamesp-epcc/DUNERucioPolicy#4]
There is a small bug in this code - 
https://github.com/jamesp-epcc/DUNERucioPolicy/blob/8fe3342e77331716fabe9372d540a7b6e39c8c5d/path_gen.py#L56

Metacat webui client get_file expects - 
------
    def get_file(self, name=None, namespace=None, fid=None, did=None, with_metadata = True, with_provenance=True):
        """Get one file record
        
        Parameters
        ----------
        fid : str, optional
            File id
        name : str, optional
        namespace : str, optional
            name and namespace must be specified together
        did : str, optional
            "nemaspace:name"
        with_metadata : boolean
            whether to include file metadata
        with_provenance:
            whether to include parents and children list

        Returns
        -------
        dict
            dictionary with file information or None if the file was not found
----
https://github.com/ivmfnal/metacat/blob/60eb2236bc732cfde3d1c533e76a4b85422d7d52/metacat/webapi/webapi.py#L633-L653

This piece of code has lfn defined as scope + name
In the lfntopfn code:

https://github.com/jamesp-epcc/DUNERucioPolicy/blob/6be5b588902d3dd7311cb0f8c0fece096810ea54/lfn2pfn.py#L44-L45

lfn = scope + ':' + name

**Comment by jamesp-epcc** [comment]
You are right - I see that the scope and name need to be passed separately to MetaCat now. I have pushed a fix and I am now able to successfully transfer a file to a non-deterministic RSE using the SURL algorithm. Please let me know if this works for you.

**Comment by ivmfnal** [comment]
this piece is not going ti work:
```
lfn = scope + ':' + name 
 jsondata = metacat_client.get_file(name=lfn) 
```

Instead, use this:
```
did = scope + ':' + name 
 jsondata = metacat_client.get_file(did=did) 
```

**Comment by ivmfnal** [comment]
To clarify, when getting metadata for a file, MetaCat API accepts it both ways (to be closer to Rucio philosophy):
1. The file can be specified with separate namespace=... and name=... arguments
2. The file can be specified with did="namespace:name"
As you understand the (2) is simply a convenience shortcut for (1)

**Comment by ivmfnal** [comment]
I would also like to have this option considered:

1. Have file names unique for the whole experiment. There are 3 ways of doing it:
a) add UUID to the file name assigned by the client
b) have MetaCat generate random file name - this feature exists already. May need to be enhanced
2. Use file name as file id when declaring the file to MetaCat
3. When computing SURL, get MetaCat file id from file file name
4. Get MetaCat info for the file by the file id instead of (scope, name) pair

**Comment by jamesp-epcc** [comment]
I'm closing this now as it works for me. Please open another issue if it is still a problem.
