### ISSUE TITLE
The Path prefix should come from Rucio configuration 

### ISSUE THREAD

**Issue by dougbenjamin** [jamesp-epcc/DUNERucioPolicy#5]
The Rucio prefix for the path should come from the RSE protocol prefix and not be hard coded - 
https://rucio.cern.ch/documentation/client_api/rseclient#add_protocol

https://github.com/jamesp-epcc/DUNERucioPolicy/blob/56c5aa913273585fe3c1030534d3620fb51455da/path_gen.py#L87

and

https://github.com/jamesp-epcc/DUNERucioPolicy/blob/56c5aa913273585fe3c1030534d3620fb51455da/lfn2pfn.py#L78

**Comment by jamesp-epcc** [comment]
I've removed the hard-coded prefix now. Only the RSE protocol prefix will be used.
