### ISSUE TITLE
Permission.py and Schema.py should be updated

### ISSUE THREAD

**Issue by bjwhite-fnal** [jamesp-epcc/DUNERucioPolicy#9]
There's been a number of changes the permissions/generic.py and schema/generic.py files in the Rucio upstream in recent versions;
Type annotations have been added to the permissions, and modifications to how the schemas are defined.

These should be reflected in DUNE's policy package for v35.

**Comment by jamesp-epcc** [comment]
You are right, there have been quite a few changes. I don't think any of them are likely to immediately break stuff, but it would be good to keep the policy package up to date. I will do this as soon as I can.

**Comment by jamesp-epcc** [comment]
I've created an updated version: https://github.com/jamesp-epcc/DUNERucioPolicy/releases/tag/rucio35b
